### ISSUE TITLE
Licence du contenu

### ISSUE THREAD

**Issue by benabel** [dav74/informatiquelycee#4]
Bonjour, je suis professeur de NSI à Nice, et j'utilise souvent ton site pour m'inspirer, merci pour la mise en ligne. Cependant je n'arrive pas à trouver d'infos sur la licence que tu utilises.

**Comment by dav74** [comment]
bonsoir,
licence creative common by sa
Bonne soirée
David Roche

<http://gplus.to/DavidRoche>david_roche_publicKey.asc
<https://drive.google.com/file/d/0B-MgHHp_RGd-RTlHYnJOUkhlUlU/view?usp=sharing>

**Comment by benabel** [comment]
Merci, tu pourrais peut-être ajouter un pied de page pour indiquer la licence.
